from .AutomaticGain import AutomaticGainContract
from .TimePowerGainContract import TimePowerGainContract
from .ExponentialGainContract import ExponentialGainContract
from .AmplitudePowerGainContract import AmplitudePowerGainContract
